FROM pytorch/pytorch:latest

# Install dependencies
RUN apt-get update \
  && apt-get install -y ffmpeg \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Install Whisper
RUN pip install -U openai_whisper -i https://pypi.tuna.tsinghua.edu.cn/simple

# Install model files
RUN whisper --model tiny dummy.wav; exit 0
RUN whisper --model base dummy.wav; exit 0
RUN whisper --model small dummy.wav; exit 0
# RUN whisper --model medium dummy.wav; exit 0
# RUN whisper --model large dummy.wav; exit 0
RUN whisper --model tiny.zh dummy.wav; exit 0
RUN whisper --model base.zh dummy.wav; exit 0
RUN whisper --model small.zh dummy.wav; exit 0
# RUN whisper --model medium.zh dummy.wav; exit 0

ENTRYPOINT ["whisper"]
CMD ["--help"]
